import os
import collections
from Bio import SeqIO
from mpl_toolkits.mplot3d import Axes3D
import matplotlib as mpl
from matplotlib import pyplot as plt
import pandas as pd
##### Target rules #####

rule all:
    input:
        # expand("test/{iteration}/simulated_reads/coverage_{coverage}.simulated.fastq",iteration=config["iterations"], coverage=config["coverages"]),
        expand("test/{iteration}/simulated_reads/coverage_{coverage}.simulated.fastq",iteration=config["iterations"], coverage=config["coverages"]),
        expand("test/{iteration}/mix_reads_distance_varied/sabin_and_distance_{distance}_coverage_200.simulated.fastq",iteration=config["iterations"], distance=config["distances"])


##### Modules #####
include: "rules/simulate_reads.smk"
include: "rules/simulate_diverse_reads.smk"


