import os
import collections
from Bio import SeqIO
from mpl_toolkits.mplot3d import Axes3D
import matplotlib as mpl
from matplotlib import pyplot as plt
import pandas as pd
##### Target rules #####

rule all:
    input:
        expand("test/{iteration}/no_mix/calls_ref/distance_0.01_coverage_{coverage}/round_2_final_phased.vcf",iteration=config["iterations"],coverage=config["coverages"]),
        expand("test/{iteration}/no_mix/calls_cns/distance_0.01_coverage_{coverage}/round_2_final_phased.vcf",iteration=config["iterations"],coverage=config["coverages"]),
        expand("test/{iteration}/alignments/distance_0.01_coverage_{coverage}X.aln.fasta",iteration=config["iterations"],coverage=config["coverages"]),
        expand("test/{iteration}/alignments/distance_0.01_coverage_{coverage}_sabin_cns.aln.fasta",iteration=config["iterations"],coverage=config["coverages"]),
        expand("test/{iteration}/alignments/distance_0.01_coverage_{coverage}_ref_cns.aln.fasta",iteration=config["iterations"],coverage=config["coverages"])

#, coverage=config["coverages"]

##### Modules #####
include: "rules/polish.smk"
include: "rules/no_mix_test.smk"


